baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonatansiracusa.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com



# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"

mpaginate: 4

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# SEO
title: "Ciencia de Datos y Finanzas - Jonatan Siracusa"
description: "Portfolio Web profesional y repositorio de proyectos de finanzas, data science, análisis de datos, machine learning aplicado a procesos de negocio y finanzas cuantitativas."
url: "https://jonatansiracusa.github.io/"
author: "Jonatan Siracusa"

